### ISSUE TITLE
TSocket read 0 bytes while creating the Index (2.0.10 version)

### ISSUE THREAD

**Issue by mars76** [tuplejump/stargate-core#46]
Hi ,

  I am using DataStax Community Edition and the Cassandra version i am using is 2.0.10

  C:\Program Files\DataStax Community\apache-cassandra\bin>nodetool -h localhost version
  Starting NodeTool
  ReleaseVersion: 2.0.10

  And i have copied the latest stargate-core jar's into my cassandra/lib folder and restarted Cassandra

  And when i tried to create the table and index using the scripts provided in your documentation i am getting the Error: "TSocket read 0 bytes"

 cqlsh:demo> CREATE KEYSPACE my_keyspace WITH replication =
                    ... {
                    ...  'class': 'SimpleStrategy',
                    ...  'replication_factor' : 1
                    ... };
cqlsh:matters_stargate> use MY_KEYSPACE;
cqlsh:my_keyspace> CREATE TABLE PERSON (
               ...     id int primary key,
               ...     isActive boolean,
               ...     age int,
               ...     eyeColor varchar,
               ...     name text,
               ...     gender varchar,
               ...     company varchar,
               ...     email varchar,
               ...     phone varchar,
               ...     address text,
               ...     stargate text
               ... );
cqlsh:my_keyspace> CREATE CUSTOM INDEX person_idx ON PERSON(stargate) USING
               ... 'com.tuplejump.stargate.RowIndex' WITH options =
               ... {
               ...         'sg_options':'{
               ...                 "fields":{
               ...                         "age":{},
               ...                         "eyeColor":{},
               ...                         "name":{},
               ...                         "gender":{},
               ...                         "company":{},
               ...                         "phone":{},
               ...                         "address":{}
               ...                         }
               ...         }'
               ... };
TSocket read 0 bytes

When i checked the logs (c:\program files\datastac community\logs\cassandra.log) i see the follwoing Error:

ERROR [Thrift:7] 2015-01-05 12:14:51,211 CustomTThreadPoolServer.java (line 219) Error occurred during processing of message.
 java.lang.RuntimeException: java.lang.ClassNotFoundException: com.tuplejump.stargate.RowIndex
	at org.apache.cassandra.db.index.SecondaryIndex.createInstance(SecondaryIndex.java:339)
	at org.apache.cassandra.config.CFMetaData.validate(CFMetaData.java:1464)
	at org.apache.cassandra.service.MigrationManager.announceColumnFamilyUpdate(MigrationManager.java:240)
	at org.apache.cassandra.cql3.statements.CreateIndexStatement.announceMigration(CreateIndexStatement.java:124)
	at org.apache.cassandra.cql3.statements.SchemaAlteringStatement.execute(SchemaAlteringStatement.java:79)
	at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:158)
	at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:175)
	at org.apache.cassandra.thrift.CassandraServer.execute_cql3_query(CassandraServer.java:1958)
	at org.apache.cassandra.thrift.Cassandra$Processor$execute_cql3_query.getResult(Cassandra.java:4486)
	at org.apache.cassandra.thrift.Cassandra$Processor$execute_cql3_query.getResult(Cassandra.java:4470)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(CustomTThreadPoolServer.java:201)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.tuplejump.stargate.RowIndex
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.apache.cassandra.db.index.SecondaryIndex.createInstance(SecondaryIndex.java:335)
	... 15 more

And the stargate-core-0.9.5.jar file is in c:\program files\datastac community\apache-cassandra\lib\ folder !!

Not sure what i am missing here.

Thanks
Sateesh

**Comment by mars76** [comment]
Tried with latest build "stargate-core-master-0.9.9" and still the same Issue.

Not sure whether i am copying the JAR Files in the correct place ? I am copying them to the lib folder of cassandra which seems right and not sure why the JARs are not getting picked up.

Am i forgetting some other setting ?

**Comment by mars76** [comment]
I installed Cassandra 2.0.9 (not as part of DataStax Community Edition) and used stargate-core 0.9.5 and didn't have this problem. Everything seems to be working as expected.

Thanks

**Comment by trulite** [comment]
This is a problem when using DSE community. This works fine when using Apache Cassandra

**Comment by eshanMewantha** [comment]
Hello,
I am using apache-cassandra-2.0.14 and stargate-core-0.9.5 and I am getting the exact same error. According to this issue 46 this shouldn't be happening when apcahe cassandra is used right? So any idea why is this occurring? 
Thank you
